# Лабораторная работа 1. Язык Python, основные библиотеки для анализа данных.

ФИО: Алескин Александр Сергеевич

Группа: 317

used python 3 

In [1]:
import numpy as np
import pandas as pd

## Часть 1: Python

#### 2. Напишите функцию `sort_tokens(s)`, которая принимает на вход строку, разделяет ее на токены по запятым, сортирует токены с помощью функции `sorted()` и снова соединяет их в одну строку через запятые. Например, для строки `u"ночь,фонарь,улица"` функция должна выдать `u"ночь,улица,фонарь"`. Придумайте несколько входных строк и протестируйте функцию на них.

Обратите внимание, что склеить строки можно с помощью конструкции `'x'.join(...)`. Например:

In [2]:
'! '.join(['i', 'am', 'very', 'excited', ':-)'])

'i! am! very! excited! :-)'

In [30]:
# исправление
def sort_tokens(s):
    x = s.split(sep =',')
    x.sort()
    return ','.join(x)    

In [31]:
st = u"ночь,фонарь,улица"
sort_tokens(st)

'ночь,улица,фонарь'

In [32]:
st = "aa"
sort_tokens(st)

'aa'

In [33]:
st = "aa,a,qq,vecw,qswe,arr"
sort_tokens(st)

'a,aa,arr,qq,qswe,vecw'

## Часть 2: NumPy и SciPy

#### 1. Повторите 1000 раз следующий эксперимент: сгенерируйте две матрицы размера $10 \times 10$ из стандартного нормального распределения, перемножьте их (как матрицы) и найдите максимальный элемент. Какое среднее значение по экспериментам у максимальных элементов? 95-процентная квантиль?

Для вычисления квантили воспользуйтесь функцией `np.percentile`

In [3]:
# исправления
import numpy as np

max_val = []
N = 1000
for i in range(N):
    a = np.random.normal(size = (10,10))
    b = np.random.normal(size = (10,10))
    a = a.dot(b) 
    max_val = max_val + [np.amax(a)]
print("expectation val of max elem: ", np.mean(max_val))
print("95-centile is: ", np.percentile(max_val, 95))

expectation val of max elem:  8.34300962809
95-centile is:  11.8841910107


#### 3. Реализуйте функцию, которая принимает на вход numpy-массив целых чисел `a`, и генерирует массив, в котором число `i` встречается `a[i]` раз. Протестируйте на результате из прошлого задания.

Обратите внимание на функцию `np.repeat`

In [38]:
#исправления
def func_easy(a):
    mas = []
    [mas.extend(np.repeat(i, a[i])) for i in range(len(a))]
    return mas

a = np.array([1, 2, 3, 4])
print(func_easy(a))
a -= 1
print(func_easy(a))
a[2] = 7
print(func_easy(a))


[0, 1, 1, 2, 2, 2, 3, 3, 3, 3]
[1, 2, 2, 3, 3, 3]
[1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3]


#### 4. Напишите функцию `scale(X)`, которая принимает на вход матрицу и масштабирует каждый ее столбец (вычитает среднее и делит на стандартное отклонение). Убедитесь, что в функции не будет происходить деления на ноль. Протестируйте на каких-нибудь данных.

In [41]:
def scale(MASS):
    MASS -= np.mean(MASS, axis = 0)
    disp = np.std(MASS, axis = 0)
    maska = disp != 0
    MASS[:, maska] = MASS[:,maska] / disp[maska]
        

In [47]:
a = np.random.normal(3,4, size= [3,3])
print(a)
scale(a)
print(a)

print(' ')
a = np.ones([3,3])
print(a)
scale(a)
print(a)

[[ 2.01498655 -0.90537843 -0.01085671]
 [ 8.97546564  3.53689911  4.62941428]
 [ 4.99555774  2.90076473 -1.84635559]]
[[-1.16214569 -1.40176276 -0.34307563]
 [ 1.27897187  0.86304142  1.35969788]
 [-0.11682617  0.53872134 -1.01662225]]
 
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


#### 5. Сгенерируйте матрицу с элементами из нормального распределения $\mathcal{N}(10, 1)$. Найдите ее:
- определитель
- след
- наименьший и наибольший элементы
- спектральную норму
- норму Фробениуса
- собственные числа
- обратную матрицу

In [44]:
a = np.random.normal(10,1, [5, 5]) 
print('array:\n', a)
print('determinant = ' , np.linalg.det(a))
print('trace =', np.trace(a))
print('max_elem =', np.max(a))
print('min_elem =', np.min(a))
print('spectral norm', np.linalg.norm(a, ord = np.inf)) #исправление
print('Frobenius norm =', np.linalg.norm(a))
print('eigenvalues =', np.linalg.eigvals(a))
print('inverse matrix:\n', np.linalg.inv(a))

array:
 [[ 10.06564123  12.20463311   9.54730031   9.35511824   9.86441043]
 [  9.44299749   9.63988579   9.24077258   9.65308549   8.91647175]
 [ 11.10190465  10.91880996  12.11141611   9.12954964   8.72545994]
 [  9.42117841   9.07724913   7.85015667   9.31247412  10.24599094]
 [  9.56486216   9.47280967  10.0256627    8.57680426   8.62835116]]
determinant =  41.7295259077
trace = 49.7577684133
max_elem = 12.2046331135
min_elem = 7.85015667085
spectral norm 51.9871403041
Frobenius norm = 48.6753486443
eigenvalues = [ 48.46149446+0.j          -0.39705622+0.70667001j  -0.39705622-0.70667001j
   1.04519319+0.46704671j   1.04519319-0.46704671j]
inverse matrix:
 [[-0.23246845 -0.07316175  2.08877143  1.14620115 -3.1319946 ]
 [ 0.41842567  0.01692723 -0.0419577  -0.2226442  -0.18904459]
 [-0.07824295 -0.18265454 -0.93838518 -0.61577592  1.95837318]
 [-0.16171746  0.96942371 -0.17123785 -0.27462853 -0.31762979]
 [ 0.0499885  -0.68887912 -1.00885402 -0.0376889   1.83559284]]
