# Лабораторная работа 1. Язык Python, основные библиотеки для анализа данных.

ФИО: Алескин Александр Сергеевич

Группа: 317

used python 3 

In [1]:
import numpy as np
import pandas as pd

## Часть 1: Python

#### 2. Напишите функцию `sort_tokens(s)`, которая принимает на вход строку, разделяет ее на токены по запятым, сортирует токены с помощью функции `sorted()` и снова соединяет их в одну строку через запятые. Например, для строки `u"ночь,фонарь,улица"` функция должна выдать `u"ночь,улица,фонарь"`. Придумайте несколько входных строк и протестируйте функцию на них.

Обратите внимание, что склеить строки можно с помощью конструкции `'x'.join(...)`. Например:

#### 3. Реализуйте функцию, которая принимает на вход numpy-массив целых чисел `a`, и генерирует массив, в котором число `i` встречается `a[i]` раз. Протестируйте на результате из прошлого задания.

Обратите внимание на функцию `np.repeat`

In [3]:
#исправления
def func_easy(a):
    mas = np.repeat(range(len(a)), a)
    return mas

a = np.array([1, 2, 3, 4])
print(func_easy(a))
a -= 1
print(func_easy(a))
a[2] = 7
print(func_easy(a))


[0 1 1 2 2 2 3 3 3 3]
[1 2 2 3 3 3]
[1 2 2 2 2 2 2 2 3 3 3]


#### 5. Сгенерируйте матрицу с элементами из нормального распределения $\mathcal{N}(10, 1)$. Найдите ее:
- определитель
- след
- наименьший и наибольший элементы
- спектральную норму
- норму Фробениуса
- собственные числа
- обратную матрицу

In [4]:
a = np.random.normal(10,1, [5, 5]) 
print('array:\n', a)
print('determinant = ' , np.linalg.det(a))
print('trace =', np.trace(a))
print('max_elem =', np.max(a))
print('min_elem =', np.min(a))
print('spectral norm', np.linalg.norm(a, ord = 2)) #исправление
print('Frobenius norm =', np.linalg.norm(a))
print('eigenvalues =', np.linalg.eigvals(a))
print('inverse matrix:\n', np.linalg.inv(a))

array:
 [[ 10.59757473  11.16188561   9.34402485  10.66164075  10.24135714]
 [ 10.61645593   9.30722467   9.59803836  11.1598372    9.99212486]
 [ 10.82904385  11.62391594  10.29391884   9.61599583  11.75768512]
 [ 10.01519171  10.89237546  10.90394775  10.18616341   9.17844769]
 [  9.08891133   9.4307014    9.22343409  10.16382228  10.54518444]]
determinant =  -167.522769436
trace = 50.9300660856
max_elem = 11.7576851217
min_elem = 9.08891133231
spectral norm 51.3297039861
Frobenius norm = 51.425971947
eigenvalues = [ 51.25719028+0.j          1.31938146+0.j         -1.25862504+0.j
  -0.19394031+1.3894281j  -0.19394031-1.3894281j]
inverse matrix:
 [[-0.0908329   0.63329073  0.38327995 -0.1781351  -0.78416353]
 [ 0.56940186 -0.53962802 -0.15201782  0.08509197  0.05376371]
 [-0.61747321  0.08294328  0.10596994  0.40553773  0.04995798]
 [ 0.3274729  -0.09167596 -0.52497159 -0.01481115  0.3670552 ]
 [-0.20648663 -0.04742415  0.21890072 -0.26299544  0.32514324]]
