# Лабораторная работа 1. Язык Python, основные библиотеки для анализа данных.

ФИО: Алескин Александр Сергеевич

Группа: 317

used python 3 

In [1]:
import numpy as np
import pandas as pd

## Часть 1: Python

#### 1. Напишите код, который сформирует список всех натуральных чисел, не превосходящих 100, которые делятся на 7 и не делятся на 5. Нельзя использовать циклы — выполните это задание с помощью list comprehension.

In [6]:
nums = [x for x in range(7,100, 7) if x%5 != 0]
nums

[7, 14, 21, 28, 42, 49, 56, 63, 77, 84, 91, 98]

#### 2. Напишите функцию `sort_tokens(s)`, которая принимает на вход строку, разделяет ее на токены по запятым, сортирует токены с помощью функции `sorted()` и снова соединяет их в одну строку через запятые. Например, для строки `u"ночь,фонарь,улица"` функция должна выдать `u"ночь,улица,фонарь"`. Придумайте несколько входных строк и протестируйте функцию на них.

Обратите внимание, что склеить строки можно с помощью конструкции `'x'.join(...)`. Например:

In [2]:
'! '.join(['i', 'am', 'very', 'excited', ':-)'])

'i! am! very! excited! :-)'

In [30]:
# исправление
def sort_tokens(s):
    x = s.split(sep =',')
    x.sort()
    return ','.join(x)    

In [31]:
st = u"ночь,фонарь,улица"
sort_tokens(st)

'ночь,улица,фонарь'

In [32]:
st = "aa"
sort_tokens(st)

'aa'

In [33]:
st = "aa,a,qq,vecw,qswe,arr"
sort_tokens(st)

'a,aa,arr,qq,qswe,vecw'

#### 3. Напишите функцию `remove_duplicates(a)`, которая принимает на вход список и возвращает его же, но без дубликатов и в отсортированном виде. Например, для списка `[u"ночь", u"улица", u"фонарь", u"аптека", u"аптека", u"улица", u"фонарь"]` результат должен быть `[u"аптека", u"ночь", u"улица", u"фонарь", ]`.

Подсказка: обратите внимание на структуру `set`!

In [61]:
def remove_duplicates(a):
    x = set(a)
    b = list(x)
    b.sort()
    return b

In [64]:
a = ['c', 'aaa', 'bbb', 'aaa', 'aaa', 'bbb', 'c']
print(a)
print(remove_duplicates(a))

['c', 'aaa', 'bbb', 'aaa', 'aaa', 'bbb', 'c']
['aaa', 'bbb', 'c']


In [65]:
a = ['c']
print(a)
print(remove_duplicates(a))

['c']
['c']


#### 4. Напишите функцию `word_counts(texts)`, которая принимает на вход список строк, и печатает пары (слово, число вхождений). Считайте, что слова в текстах могут быть разделены только пробелами. Например, для входа `[u'ночь улица фонарь аптека', u'аптека улица фонарь']` должно быть напечатано
>аптека 2

>улица 2

>фонарь 2

>ночь 1

Подсказки:

Чтобы разбить каждый из текстов на слова, воспользуйтесь функцией `map`, которая применяет заданную функцию к каждому элементу списка. Например, если бы нужно было каждый из текстов привести к нижнему регистру, то команда выглядела бы так:

In [71]:
map(lambda x: x.lower(), [u"abCDefg", u"HIjkL"])

После первого шага вы получите список, состоящий из списков слов. Чтобы объединить их в один список слов, воспользуйтесь функцией `reduce`. Например, просуммировать числа из списка с ее помощью можно так:



In [70]:
reduce(lambda x, y: x + y, [1, 2, 3, 4, 5])

NameError: name 'reduce' is not defined

Для подсчета количества вхождений слов воспользуйтесь структурой `defaultdict` из модуля `collections`. В отличие от обычного `dict`, она не генерирует ошибку при обращении к несуществущему ключу, а создает новую запись, инициализируемую нулевым значением. Например:

In [75]:
from collections import defaultdict
d = defaultdict(int)
print(d)
d['abc'] += 1
print(d)
d['xxx']
print(d)

defaultdict(<class 'int'>, {})
defaultdict(<class 'int'>, {'abc': 1})
defaultdict(<class 'int'>, {'xxx': 0, 'abc': 1})


In [98]:
# my code starts
from itertools import chain
from collections import defaultdict
def word_counts(texts):
    d = defaultdict(int)
    words = []
    words_list = map(lambda x: x.split(' '), texts)
    for x in words_list:
        words += x
    for x in words:
        d[x] += 1
    for x in d.keys():
        print(x, d[x])


In [99]:
str_list = [u'ночь улица фонарь аптека', u'аптека улица фонарь']
str_list
word_counts(str_list)

ночь 1
фонарь 2
улица 2
аптека 2


In [101]:
str_list = []
str_list
word_counts(str_list)

In [102]:
str_list = ['a a a a', 'a b b a b', 'c b a']
str_list
word_counts(str_list)

b 4
c 1
a 7


#### 5. (бонусное задание) Скачайте английский перевод "Преступления и наказания". Найдите 20 самых популярных слов и 20 слов, которые встречаются только один раз.

Приведите текст к нижнему регистру. Удалите из него все специальные символы и цифры. Разделите текст на слова, считая разделителями все, кроме букв. Обратите внимание на функцию `split` из модуля `re`.

Не забудьте удалить пустые слова:
```
words = filter(lambda x: len(x) > 0, words)
```

In [68]:
from urllib import urlopen
url = "http://www.gutenberg.org/files/2554/2554.txt"
response = urlopen(url)
raw_text = response.read().decode('utf8')

ImportError: cannot import name 'urlopen'

In [7]:
raw_text[1000:1100]

u'r five\r\nchildren in only two rooms. The father and mother spent their evenings\r\nin reading aloud to '

## Часть 2: NumPy и SciPy

#### 1. Повторите 1000 раз следующий эксперимент: сгенерируйте две матрицы размера $10 \times 10$ из стандартного нормального распределения, перемножьте их (как матрицы) и найдите максимальный элемент. Какое среднее значение по экспериментам у максимальных элементов? 95-процентная квантиль?

Для вычисления квантили воспользуйтесь функцией `np.percentile`

In [5]:
# исправления
import numpy as np

max_val = []
N = 1000
for i in range(N):
    a = np.random.normal(size = (10,10))
    b = np.random.normal(size = (10,10))
    a = a.dot(b) 
    max_val = max_val + [np.amax(a)]
print("expectation val of max elem: ", np.mean(max_val))
print("95-centile is: ", np.percentile(max_val, 95))

expectation val of max elem:  8.47124629934
95-centile is:  11.8082843536


#### 2. Сгенерируйте 1000 чисел из распределения Пуассона с параметром $\lambda = 5$. Сформируйте массив, в котором в i-м элементе будет записано количество сгенерированных чисел, равных i.


Обратите внимание на функцию `np.bincount`

In [133]:
a = np.random.poisson(lam = 5, size = [1000])
val_count = np.bincount(a)
print(val_count)

[ 10  24  82 158 167 187 145 100  69  29  17   9   0   2   1]


#### 3. Реализуйте функцию, которая принимает на вход numpy-массив целых чисел `a`, и генерирует массив, в котором число `i` встречается `a[i]` раз. Протестируйте на результате из прошлого задания.

Обратите внимание на функцию `np.repeat`

In [48]:
#исправления 
def func_easy(a):
    mas = []
    [mas.extend(np.repeat(i, a[i])) for i in range(len(a))]
    return mas

a = np.array([1, 2, 3, 4])
print(func_easy(a))
a -= 1
print(func_easy(a))
a[2] = 7
print(func_easy(a))

        

[0, 1, 1, 2, 2, 2, 3, 3, 3, 3]
[1, 2, 2, 3, 3, 3]
[1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3]


#### 4. Напишите функцию `scale(X)`, которая принимает на вход матрицу и масштабирует каждый ее столбец (вычитает среднее и делит на стандартное отклонение). Убедитесь, что в функции не будет происходить деления на ноль. Протестируйте на каких-нибудь данных.

In [41]:
def scale(MASS):
    MASS -= np.mean(MASS, axis = 0)
    disp = np.std(MASS, axis = 0)
    maska = disp != 0
    MASS[:, maska] = MASS[:,maska] / disp[maska]
        

In [47]:
a = np.random.normal(3,4, size= [3,3])
print(a)
scale(a)
print(a)

print(' ')
a = np.ones([3,3])
print(a)
scale(a)
print(a)

[[ 2.01498655 -0.90537843 -0.01085671]
 [ 8.97546564  3.53689911  4.62941428]
 [ 4.99555774  2.90076473 -1.84635559]]
[[-1.16214569 -1.40176276 -0.34307563]
 [ 1.27897187  0.86304142  1.35969788]
 [-0.11682617  0.53872134 -1.01662225]]
 
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


#### 5. Сгенерируйте матрицу с элементами из нормального распределения $\mathcal{N}(10, 1)$. Найдите ее:
- определитель
- след
- наименьший и наибольший элементы
- спектральную норму
- норму Фробениуса
- собственные числа
- обратную матрицу

In [44]:
a = np.random.normal(10,1, [5, 5]) 
print('array:\n', a)
print('determinant = ' , np.linalg.det(a))
print('trace =', np.trace(a))
print('max_elem =', np.max(a))
print('min_elem =', np.min(a))
print('spectral norm', np.linalg.norm(a, ord = np.inf)) #исправление
print('Frobenius norm =', np.linalg.norm(a))
print('eigenvalues =', np.linalg.eigvals(a))
print('inverse matrix:\n', np.linalg.inv(a))

array:
 [[ 10.06564123  12.20463311   9.54730031   9.35511824   9.86441043]
 [  9.44299749   9.63988579   9.24077258   9.65308549   8.91647175]
 [ 11.10190465  10.91880996  12.11141611   9.12954964   8.72545994]
 [  9.42117841   9.07724913   7.85015667   9.31247412  10.24599094]
 [  9.56486216   9.47280967  10.0256627    8.57680426   8.62835116]]
determinant =  41.7295259077
trace = 49.7577684133
max_elem = 12.2046331135
min_elem = 7.85015667085
spectral norm 51.9871403041
Frobenius norm = 48.6753486443
eigenvalues = [ 48.46149446+0.j          -0.39705622+0.70667001j  -0.39705622-0.70667001j
   1.04519319+0.46704671j   1.04519319-0.46704671j]
inverse matrix:
 [[-0.23246845 -0.07316175  2.08877143  1.14620115 -3.1319946 ]
 [ 0.41842567  0.01692723 -0.0419577  -0.2226442  -0.18904459]
 [-0.07824295 -0.18265454 -0.93838518 -0.61577592  1.95837318]
 [-0.16171746  0.96942371 -0.17123785 -0.27462853 -0.31762979]
 [ 0.0499885  -0.68887912 -1.00885402 -0.0376889   1.83559284]]


## Часть 3: Pandas

#### Ответьте на вопросы о данных по авиарейсам в США за январь-апрель 2008 года.

Данные: http://stat-computing.org/dataexpo/2009/2008.csv.bz2
(обратите внимание, что распаковывать этот файл не обязательно — функция `pandas.read_csv` умеет читать из архивов автоматически)

Описание: http://stat-computing.org/dataexpo/2009/the-data.html

1. Какая из причин отмены рейса (`CancellationCode`) была самой частой? (расшифровки кодов можно найти в описании данных)
2. Найдите среднее, минимальное и максимальное расстояние, пройденное самолетом.
3. Не выглядит ли подозрительным минимальное пройденное расстояние? В какие дни и на каких рейсах оно было? Какое расстояние было пройдено этими же рейсами в другие дни?
4. Из какого аэропорта было произведено больше всего вылетов? В каком городе он находится?
5. Найдите для каждого аэропорта среднее время полета (`AirTime`) по всем вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?
6. Найдите аэропорт, у которого наибольшая доля задержанных (`DepDelay > 0`) рейсов. Исключите при этом из рассмотрения аэропорты, из которых было отправлено меньше 1000 рейсов (используйте функцию `filter` после `groupby`).

In [1]:
import pandas as pd

In [3]:
data = pd.read_csv('2008.csv')
# файл слишком большой

MemoryError: 

In [2]:
data = pd.read_csv('/home/alex/Загрузки/2008_short.csv')

In [35]:
# - 1
stat = data.CancellationCode.value_counts()
sign = stat.argmax()
print('The most common cause of flight cancellation is', end = ' ')
if sign == 'A':
    print('carrier')
elif sign == 'B':
    print('weather')
elif sign == 'C':
    print('NAS')
elif sign == 'D':
    print('security')

The most common cause of flight cancellation is carrier


In [37]:
# - 2
print('max distance:', data.Distance.max(), ' miles')
print('average dist:', round(data.Distance.mean()),' miles')
print('min distance:', data.Distance.min(), ' miles')

max distance: 2363  miles
average dist: 630  miles
min distance: 133  miles


In [102]:
# - 3
print('Yes, it looks weird :)')
half_data = data[[ 'Year', 'Month', 'DayofMonth','UniqueCarrier', 'FlightNum']]
print_data = half_data[data.Distance == data.Distance.min()]
print_data

Yes, it looks weird :)


Year  Month  DayofMonth UniqueCarrier  FlightNum
657   2008      1           3            WN        150
658   2008      1           3            WN        907
659   2008      1           3            WN       2368
660   2008      1           3            WN       3398
1662  2008      1           3            WN        467
1663  2008      1           3            WN        630
1664  2008      1           3            WN       1305
1665  2008      1           3            WN       3754
4094  2008      1           4            WN        150
4095  2008      1           4            WN        907
4096  2008      1           4            WN       2368
4097  2008      1           4            WN       3398
5100  2008      1           4            WN        467
5101  2008      1           4            WN        630
5102  2008      1           4            WN       1305
5103  2008      1           4            WN       3754
7234  2008      1           5            WN        150
7235  2008      1           5            WN       2368
7236  2008      1           5            WN       3398
7237  2008      1           5            WN       3773
8050  2008      1           5            WN        630
8051  2008      1           5            WN        837
8052  2008      1           5            WN       1305
8053  2008      1           5            WN       3754

In [166]:
uniq_num = print_data.FlightNum.unique()
uniq_car = print_data.UniqueCarrier.unique()
for i in uniq_car:
    for j in uniq_num:
        print('Flight ', i, j)
        mask = (data.FlightNum == j) & (data.UniqueCarrier == i) & (data.Distance != data.Distance.min())
        print(data.Distance[mask])

Flight  WN 150
2598    616
8836    616
Name: Distance, dtype: int64
Flight  WN 907
1286    861
4724    861
Name: Distance, dtype: int64
Flight  WN 2368
1572    1073
5010    1073
7974    1073
Name: Distance, dtype: int64
Flight  WN 3398
34      972
3471    972
6702    972
9638    972
Name: Distance, dtype: int64
Flight  WN 467
631     550
935     437
2394    677
2962    580
4068    550
4373    437
8639    677
9176    580
Name: Distance, dtype: int64
Flight  WN 630
607     972
4044    972
7183    972
Name: Distance, dtype: int64
Flight  WN 1305
650     1073
4087    1073
7227    1073
Name: Distance, dtype: int64
Flight  WN 3754
652     1073
4089    1073
7229    1073
Name: Distance, dtype: int64
Flight  WN 3773
2668    1011
6066    1011
8903    1011
Name: Distance, dtype: int64
Flight  WN 837
639     861
4076    861
7217    861
Name: Distance, dtype: int64


In [7]:
# - 4
airport = pd.read_csv('/home/alex/Загрузки/airports.csv')
max_fly_airport = (data.Origin.value_counts()).argmax()
info = airport[airport.iata == max_fly_airport]
print('The airport is ')
info[[1,2]]

The airport is 


airport       city
2037  McCarran International  Las Vegas

In [163]:
# 5 Найдите для каждого аэропорта среднее время полета (AirTime) 
# по всем вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?

print_data2 = data.groupby('Origin').AirTime.mean()
print_data2[1:10]

Origin
ALB    112.350000
AMA     57.968750
AUS     85.411765
BDL    108.759259
BHM     82.525000
BNA    114.115226
BOI     61.545455
BUF    111.291667
BUR     55.560510
Name: AirTime, dtype: float64

In [101]:
airtime_airport = print_data2.argmax()
info = airport[airport.iata == airtime_airport]
print('The airport is ')
info[[1,2]]

The airport is 


airport   city
1886  Long Island - MacArthur  Islip

In [161]:
# 6 Найдите аэропорт, у которого наибольшая доля задержанных (DepDelay > 0) рейсов. 
# Исключите при этом из рассмотрения аэропорты,
# из которых было отправлено меньше 1000 рейсов (используйте функцию filter после groupby).
# a.a :Так как данных только часть, то 1000 заменено на 300.

vals = data.Origin.value_counts()
vals = vals[vals > 300] # only over 300 now
plus_del = data.Origin[data.DepDelay > 0].value_counts()
plus_del = plus_del[vals.axes[0]]

print((plus_del/vals).argmax())

MDW
